// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command struct {
	Signer    string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Price     int32  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*Command_Bootstrap
	//	*Command_CommandJournalCreate
	//	*Command_CommandJournalUpdateProperties
	//	*Command_CommandJournalUpdateAuthorization
	//	*Command_CommandJournalEditorAcceptDuty
	//	*Command_CommandJournalEditorInvite
	//	*Command_CommandJournalEditorResign
	//	*Command_CommandVolumeCreate
	//	*Command_CommandSettingsUpdate
	//	*Command_PersonCreate
	//	*Command_CommandPersonUpdateProperties
	//	*Command_CommandUpdateAuthorization
	//	*Command_CommandPersonUpdateBalanceIncrement
	//	*Command_CommandManuscriptCreate
	//	*Command_CommandManuscriptCreateNewVersion
	//	*Command_CommandManuscriptAcceptAuthorship
	//	*Command_CommandManuscriptAllowReview
	//	*Command_CommandWriteReview
	Body                 isCommand_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *Command) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Command) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type isCommand_Body interface {
	isCommand_Body()
}

type Command_Bootstrap struct {
	Bootstrap *CommandBootstrap `protobuf:"bytes,4,opt,name=bootstrap,proto3,oneof"`
}

type Command_CommandJournalCreate struct {
	CommandJournalCreate *CommandJournalCreate `protobuf:"bytes,5,opt,name=commandJournalCreate,proto3,oneof"`
}

type Command_CommandJournalUpdateProperties struct {
	CommandJournalUpdateProperties *CommandJournalUpdateProperties `protobuf:"bytes,6,opt,name=commandJournalUpdateProperties,proto3,oneof"`
}

type Command_CommandJournalUpdateAuthorization struct {
	CommandJournalUpdateAuthorization *CommandJournalUpdateAuthorization `protobuf:"bytes,7,opt,name=commandJournalUpdateAuthorization,proto3,oneof"`
}

type Command_CommandJournalEditorAcceptDuty struct {
	CommandJournalEditorAcceptDuty *CommandJournalEditorAcceptDuty `protobuf:"bytes,8,opt,name=commandJournalEditorAcceptDuty,proto3,oneof"`
}

type Command_CommandJournalEditorInvite struct {
	CommandJournalEditorInvite *CommandJournalEditorInvite `protobuf:"bytes,9,opt,name=commandJournalEditorInvite,proto3,oneof"`
}

type Command_CommandJournalEditorResign struct {
	CommandJournalEditorResign *CommandJournalEditorResign `protobuf:"bytes,10,opt,name=commandJournalEditorResign,proto3,oneof"`
}

type Command_CommandVolumeCreate struct {
	CommandVolumeCreate *CommandVolumeCreate `protobuf:"bytes,11,opt,name=commandVolumeCreate,proto3,oneof"`
}

type Command_CommandSettingsUpdate struct {
	CommandSettingsUpdate *CommandSettingsUpdate `protobuf:"bytes,12,opt,name=commandSettingsUpdate,proto3,oneof"`
}

type Command_PersonCreate struct {
	PersonCreate *CommandPersonCreate `protobuf:"bytes,13,opt,name=personCreate,proto3,oneof"`
}

type Command_CommandPersonUpdateProperties struct {
	CommandPersonUpdateProperties *CommandPersonUpdateProperties `protobuf:"bytes,14,opt,name=commandPersonUpdateProperties,proto3,oneof"`
}

type Command_CommandUpdateAuthorization struct {
	CommandUpdateAuthorization *CommandPersonUpdateAuthorization `protobuf:"bytes,15,opt,name=commandUpdateAuthorization,proto3,oneof"`
}

type Command_CommandPersonUpdateBalanceIncrement struct {
	CommandPersonUpdateBalanceIncrement *CommandPersonUpdateBalanceIncrement `protobuf:"bytes,16,opt,name=commandPersonUpdateBalanceIncrement,proto3,oneof"`
}

type Command_CommandManuscriptCreate struct {
	CommandManuscriptCreate *CommandManuscriptCreate `protobuf:"bytes,17,opt,name=commandManuscriptCreate,proto3,oneof"`
}

type Command_CommandManuscriptCreateNewVersion struct {
	CommandManuscriptCreateNewVersion *CommandManuscriptCreateNewVersion `protobuf:"bytes,18,opt,name=commandManuscriptCreateNewVersion,proto3,oneof"`
}

type Command_CommandManuscriptAcceptAuthorship struct {
	CommandManuscriptAcceptAuthorship *CommandManuscriptAcceptAuthorship `protobuf:"bytes,19,opt,name=commandManuscriptAcceptAuthorship,proto3,oneof"`
}

type Command_CommandManuscriptAllowReview struct {
	CommandManuscriptAllowReview *CommandManuscriptAllowReview `protobuf:"bytes,20,opt,name=commandManuscriptAllowReview,proto3,oneof"`
}

type Command_CommandWriteReview struct {
	CommandWriteReview *CommandWriteReview `protobuf:"bytes,21,opt,name=commandWriteReview,proto3,oneof"`
}

func (*Command_Bootstrap) isCommand_Body() {}

func (*Command_CommandJournalCreate) isCommand_Body() {}

func (*Command_CommandJournalUpdateProperties) isCommand_Body() {}

func (*Command_CommandJournalUpdateAuthorization) isCommand_Body() {}

func (*Command_CommandJournalEditorAcceptDuty) isCommand_Body() {}

func (*Command_CommandJournalEditorInvite) isCommand_Body() {}

func (*Command_CommandJournalEditorResign) isCommand_Body() {}

func (*Command_CommandVolumeCreate) isCommand_Body() {}

func (*Command_CommandSettingsUpdate) isCommand_Body() {}

func (*Command_PersonCreate) isCommand_Body() {}

func (*Command_CommandPersonUpdateProperties) isCommand_Body() {}

func (*Command_CommandUpdateAuthorization) isCommand_Body() {}

func (*Command_CommandPersonUpdateBalanceIncrement) isCommand_Body() {}

func (*Command_CommandManuscriptCreate) isCommand_Body() {}

func (*Command_CommandManuscriptCreateNewVersion) isCommand_Body() {}

func (*Command_CommandManuscriptAcceptAuthorship) isCommand_Body() {}

func (*Command_CommandManuscriptAllowReview) isCommand_Body() {}

func (*Command_CommandWriteReview) isCommand_Body() {}

func (m *Command) GetBody() isCommand_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Command) GetBootstrap() *CommandBootstrap {
	if x, ok := m.GetBody().(*Command_Bootstrap); ok {
		return x.Bootstrap
	}
	return nil
}

func (m *Command) GetCommandJournalCreate() *CommandJournalCreate {
	if x, ok := m.GetBody().(*Command_CommandJournalCreate); ok {
		return x.CommandJournalCreate
	}
	return nil
}

func (m *Command) GetCommandJournalUpdateProperties() *CommandJournalUpdateProperties {
	if x, ok := m.GetBody().(*Command_CommandJournalUpdateProperties); ok {
		return x.CommandJournalUpdateProperties
	}
	return nil
}

func (m *Command) GetCommandJournalUpdateAuthorization() *CommandJournalUpdateAuthorization {
	if x, ok := m.GetBody().(*Command_CommandJournalUpdateAuthorization); ok {
		return x.CommandJournalUpdateAuthorization
	}
	return nil
}

func (m *Command) GetCommandJournalEditorAcceptDuty() *CommandJournalEditorAcceptDuty {
	if x, ok := m.GetBody().(*Command_CommandJournalEditorAcceptDuty); ok {
		return x.CommandJournalEditorAcceptDuty
	}
	return nil
}

func (m *Command) GetCommandJournalEditorInvite() *CommandJournalEditorInvite {
	if x, ok := m.GetBody().(*Command_CommandJournalEditorInvite); ok {
		return x.CommandJournalEditorInvite
	}
	return nil
}

func (m *Command) GetCommandJournalEditorResign() *CommandJournalEditorResign {
	if x, ok := m.GetBody().(*Command_CommandJournalEditorResign); ok {
		return x.CommandJournalEditorResign
	}
	return nil
}

func (m *Command) GetCommandVolumeCreate() *CommandVolumeCreate {
	if x, ok := m.GetBody().(*Command_CommandVolumeCreate); ok {
		return x.CommandVolumeCreate
	}
	return nil
}

func (m *Command) GetCommandSettingsUpdate() *CommandSettingsUpdate {
	if x, ok := m.GetBody().(*Command_CommandSettingsUpdate); ok {
		return x.CommandSettingsUpdate
	}
	return nil
}

func (m *Command) GetPersonCreate() *CommandPersonCreate {
	if x, ok := m.GetBody().(*Command_PersonCreate); ok {
		return x.PersonCreate
	}
	return nil
}

func (m *Command) GetCommandPersonUpdateProperties() *CommandPersonUpdateProperties {
	if x, ok := m.GetBody().(*Command_CommandPersonUpdateProperties); ok {
		return x.CommandPersonUpdateProperties
	}
	return nil
}

func (m *Command) GetCommandUpdateAuthorization() *CommandPersonUpdateAuthorization {
	if x, ok := m.GetBody().(*Command_CommandUpdateAuthorization); ok {
		return x.CommandUpdateAuthorization
	}
	return nil
}

func (m *Command) GetCommandPersonUpdateBalanceIncrement() *CommandPersonUpdateBalanceIncrement {
	if x, ok := m.GetBody().(*Command_CommandPersonUpdateBalanceIncrement); ok {
		return x.CommandPersonUpdateBalanceIncrement
	}
	return nil
}

func (m *Command) GetCommandManuscriptCreate() *CommandManuscriptCreate {
	if x, ok := m.GetBody().(*Command_CommandManuscriptCreate); ok {
		return x.CommandManuscriptCreate
	}
	return nil
}

func (m *Command) GetCommandManuscriptCreateNewVersion() *CommandManuscriptCreateNewVersion {
	if x, ok := m.GetBody().(*Command_CommandManuscriptCreateNewVersion); ok {
		return x.CommandManuscriptCreateNewVersion
	}
	return nil
}

func (m *Command) GetCommandManuscriptAcceptAuthorship() *CommandManuscriptAcceptAuthorship {
	if x, ok := m.GetBody().(*Command_CommandManuscriptAcceptAuthorship); ok {
		return x.CommandManuscriptAcceptAuthorship
	}
	return nil
}

func (m *Command) GetCommandManuscriptAllowReview() *CommandManuscriptAllowReview {
	if x, ok := m.GetBody().(*Command_CommandManuscriptAllowReview); ok {
		return x.CommandManuscriptAllowReview
	}
	return nil
}

func (m *Command) GetCommandWriteReview() *CommandWriteReview {
	if x, ok := m.GetBody().(*Command_CommandWriteReview); ok {
		return x.CommandWriteReview
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Command) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Command_Bootstrap)(nil),
		(*Command_CommandJournalCreate)(nil),
		(*Command_CommandJournalUpdateProperties)(nil),
		(*Command_CommandJournalUpdateAuthorization)(nil),
		(*Command_CommandJournalEditorAcceptDuty)(nil),
		(*Command_CommandJournalEditorInvite)(nil),
		(*Command_CommandJournalEditorResign)(nil),
		(*Command_CommandVolumeCreate)(nil),
		(*Command_CommandSettingsUpdate)(nil),
		(*Command_PersonCreate)(nil),
		(*Command_CommandPersonUpdateProperties)(nil),
		(*Command_CommandUpdateAuthorization)(nil),
		(*Command_CommandPersonUpdateBalanceIncrement)(nil),
		(*Command_CommandManuscriptCreate)(nil),
		(*Command_CommandManuscriptCreateNewVersion)(nil),
		(*Command_CommandManuscriptAcceptAuthorship)(nil),
		(*Command_CommandManuscriptAllowReview)(nil),
		(*Command_CommandWriteReview)(nil),
	}
}

func init() {
	proto.RegisterType((*Command)(nil), "Command")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor_213c0bb044472049) }

var fileDescriptor_213c0bb044472049 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x95, 0x41, 0x4f, 0xdb, 0x3e,
	0x18, 0xc6, 0xdd, 0x3f, 0xb4, 0xfc, 0x6b, 0x28, 0x03, 0xb7, 0x65, 0x16, 0x03, 0x56, 0xd8, 0x0e,
	0x3d, 0x21, 0x6d, 0xbb, 0xed, 0x46, 0x19, 0x92, 0xd9, 0x34, 0x84, 0xbc, 0x8d, 0x49, 0x93, 0x76,
	0x48, 0xd3, 0x77, 0xe0, 0x29, 0xb1, 0x23, 0xc7, 0xa5, 0x63, 0x9f, 0x79, 0x1f, 0x62, 0xc2, 0x71,
	0x68, 0x92, 0x3a, 0x65, 0x47, 0xfb, 0x79, 0xde, 0xdf, 0x63, 0xc7, 0xaf, 0x1d, 0xdc, 0x09, 0x55,
	0x1c, 0x07, 0x72, 0x72, 0x9c, 0x68, 0x65, 0xd4, 0xee, 0x46, 0x02, 0x3a, 0x55, 0xd2, 0x8d, 0x3a,
	0x3f, 0xd5, 0x54, 0xcb, 0x20, 0x72, 0xc3, 0xcd, 0x14, 0x8c, 0x11, 0xf2, 0x3a, 0x75, 0xe3, 0xad,
	0x38, 0x90, 0xd3, 0x34, 0xd4, 0x22, 0x31, 0xd9, 0xcc, 0xd1, 0x9f, 0x0e, 0x5e, 0x3b, 0xcd, 0x80,
	0x64, 0x07, 0xb7, 0x52, 0x71, 0x2d, 0x41, 0xd3, 0xc6, 0xa0, 0x31, 0x6c, 0x73, 0x37, 0x22, 0x3d,
	0xdc, 0x4c, 0xb4, 0x08, 0x81, 0xfe, 0x37, 0x68, 0x0c, 0x9b, 0x3c, 0x1b, 0x90, 0x3d, 0xdc, 0x36,
	0x22, 0x86, 0xd4, 0x04, 0x71, 0x42, 0x57, 0x06, 0x8d, 0xe1, 0x0a, 0x9f, 0x4f, 0x90, 0x57, 0xb8,
	0x3d, 0x56, 0xca, 0xa4, 0x46, 0x07, 0x09, 0x5d, 0x1d, 0x34, 0x86, 0xeb, 0xaf, 0xb7, 0x8f, 0x5d,
	0xd0, 0x28, 0x17, 0x18, 0xe2, 0x73, 0x17, 0xf9, 0x80, 0x7b, 0x6e, 0x6b, 0xef, 0xb3, 0x4d, 0x9c,
	0x6a, 0x08, 0x0c, 0xd0, 0xa6, 0xad, 0xee, 0xe7, 0xd5, 0x25, 0x91, 0x21, 0xee, 0x2d, 0x22, 0x02,
	0x1f, 0x94, 0xe7, 0xbf, 0x24, 0x93, 0xc0, 0xc0, 0xa5, 0x56, 0x09, 0x68, 0x23, 0x20, 0xa5, 0x2d,
	0x8b, 0x7d, 0x5e, 0xc1, 0x56, 0x6d, 0x0c, 0xf1, 0x47, 0x40, 0x44, 0xe3, 0x43, 0x9f, 0xe3, 0x64,
	0x6a, 0x6e, 0x94, 0x16, 0xbf, 0x03, 0x23, 0x94, 0xa4, 0x6b, 0x36, 0xed, 0xc8, 0x9b, 0x56, 0x72,
	0x32, 0xc4, 0x1f, 0xc7, 0x2d, 0x6e, 0xef, 0x6c, 0x22, 0x8c, 0xd2, 0x27, 0x61, 0x08, 0x89, 0x79,
	0x37, 0x35, 0x77, 0xf4, 0x7f, 0xef, 0xf6, 0xaa, 0xb6, 0xc5, 0xed, 0x55, 0x1d, 0xe4, 0x3b, 0xde,
	0xf5, 0x39, 0xce, 0xe5, 0xad, 0x30, 0x40, 0xdb, 0x36, 0xe6, 0x99, 0x37, 0x26, 0xb3, 0x30, 0xc4,
	0x97, 0x00, 0xea, 0xf0, 0x1c, 0xee, 0x9b, 0x8f, 0xe2, 0x25, 0xf8, 0xcc, 0x52, 0x87, 0xcf, 0x54,
	0xc2, 0x70, 0xd7, 0xa9, 0x57, 0x2a, 0x9a, 0xc6, 0xe0, 0x7a, 0x6a, 0xdd, 0x72, 0x7b, 0x39, 0xb7,
	0xa8, 0x31, 0xc4, 0x7d, 0x25, 0xe4, 0x02, 0xf7, 0xdd, 0xf4, 0x27, 0x77, 0xa9, 0xb2, 0x83, 0xa1,
	0x1b, 0x96, 0xb5, 0x93, 0xb3, 0xca, 0x2a, 0x43, 0xdc, 0x5f, 0x46, 0xde, 0x62, 0x77, 0x75, 0xdd,
	0x92, 0x3a, 0xe5, 0x25, 0x5d, 0x16, 0x34, 0x86, 0x78, 0xc9, 0x4b, 0x7e, 0xe0, 0xfd, 0xb0, 0x68,
	0x5b, 0x68, 0xee, 0x4d, 0x0b, 0x3b, 0x28, 0xc3, 0x3c, 0xbd, 0xbd, 0x1c, 0x43, 0xc2, 0x87, 0xc3,
	0xf1, 0xf5, 0xf4, 0x13, 0x1b, 0x72, 0xe8, 0x0b, 0xa9, 0xb6, 0xf4, 0x12, 0x0c, 0xf9, 0x85, 0x5f,
	0x78, 0x56, 0x31, 0x0a, 0xa2, 0x40, 0x86, 0x70, 0x2e, 0x43, 0x0d, 0x31, 0x48, 0x43, 0xb7, 0x6c,
	0xda, 0x4b, 0x5f, 0x5a, 0xd5, 0xcb, 0x10, 0xff, 0x17, 0x24, 0xf9, 0x8c, 0x9f, 0x3a, 0xdb, 0xc7,
	0x87, 0x77, 0xd1, 0x9d, 0xc6, 0xb6, 0x4d, 0xa3, 0x79, 0x5a, 0x55, 0x67, 0x88, 0xd7, 0x95, 0x16,
	0xde, 0x83, 0xaa, 0x74, 0x01, 0xb3, 0x2b, 0xd0, 0xe9, 0xfd, 0xb7, 0x23, 0xe5, 0xf7, 0xa0, 0xde,
	0x59, 0x78, 0x0f, 0xea, 0x4d, 0xde, 0xcc, 0xec, 0x0e, 0x67, 0xdf, 0x3a, 0xbd, 0x11, 0x09, 0xed,
	0xd6, 0x65, 0x56, 0x9d, 0xde, 0xcc, 0xaa, 0x89, 0x84, 0x78, 0x6f, 0xd1, 0x14, 0x45, 0x6a, 0xc6,
	0xe1, 0x56, 0xc0, 0x8c, 0xf6, 0x6c, 0xdc, 0xbe, 0x27, 0x6e, 0x6e, 0x62, 0x88, 0x2f, 0x85, 0x90,
	0x33, 0x4c, 0x9c, 0xfe, 0x55, 0x0b, 0x03, 0x0e, 0xdd, 0xb7, 0xe8, 0x6e, 0x8e, 0x2e, 0x48, 0x0c,
	0x71, 0x4f, 0xc1, 0xa8, 0x85, 0x57, 0xc7, 0x6a, 0x72, 0x37, 0x5a, 0xfb, 0xd6, 0x8c, 0xd5, 0x04,
	0xa2, 0x71, 0xcb, 0xfe, 0xfe, 0xde, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x93, 0xdd, 0x39,
	0x4e, 0x07, 0x00, 0x00,
}
