// Code generated by protoc-gen-go. DO NOT EDIT.
// source: journal.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EditorState int32

const (
	EditorState_editorProposed EditorState = 0
	EditorState_editorAccepted EditorState = 1
)

var EditorState_name = map[int32]string{
	0: "editorProposed",
	1: "editorAccepted",
}

var EditorState_value = map[string]int32{
	"editorProposed": 0,
	"editorAccepted": 1,
}

func (x EditorState) String() string {
	return proto.EnumName(EditorState_name, int32(x))
}

func (EditorState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{0}
}

type StateJournal struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedOn            int64         `protobuf:"varint,2,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	ModifiedOn           int64         `protobuf:"varint,3,opt,name=modifiedOn,proto3" json:"modifiedOn,omitempty"`
	Title                string        `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	IsSigned             bool          `protobuf:"varint,5,opt,name=isSigned,proto3" json:"isSigned,omitempty"`
	DescriptionHash      string        `protobuf:"bytes,6,opt,name=descriptionHash,proto3" json:"descriptionHash,omitempty"`
	EditorInfo           []*EditorInfo `protobuf:"bytes,7,rep,name=editorInfo,proto3" json:"editorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StateJournal) Reset()         { *m = StateJournal{} }
func (m *StateJournal) String() string { return proto.CompactTextString(m) }
func (*StateJournal) ProtoMessage()    {}
func (*StateJournal) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{0}
}

func (m *StateJournal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateJournal.Unmarshal(m, b)
}
func (m *StateJournal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateJournal.Marshal(b, m, deterministic)
}
func (m *StateJournal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateJournal.Merge(m, src)
}
func (m *StateJournal) XXX_Size() int {
	return xxx_messageInfo_StateJournal.Size(m)
}
func (m *StateJournal) XXX_DiscardUnknown() {
	xxx_messageInfo_StateJournal.DiscardUnknown(m)
}

var xxx_messageInfo_StateJournal proto.InternalMessageInfo

func (m *StateJournal) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StateJournal) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *StateJournal) GetModifiedOn() int64 {
	if m != nil {
		return m.ModifiedOn
	}
	return 0
}

func (m *StateJournal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *StateJournal) GetIsSigned() bool {
	if m != nil {
		return m.IsSigned
	}
	return false
}

func (m *StateJournal) GetDescriptionHash() string {
	if m != nil {
		return m.DescriptionHash
	}
	return ""
}

func (m *StateJournal) GetEditorInfo() []*EditorInfo {
	if m != nil {
		return m.EditorInfo
	}
	return nil
}

type EditorInfo struct {
	EditorId             string      `protobuf:"bytes,1,opt,name=editorId,proto3" json:"editorId,omitempty"`
	EditorState          EditorState `protobuf:"varint,2,opt,name=editorState,proto3,enum=EditorState" json:"editorState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EditorInfo) Reset()         { *m = EditorInfo{} }
func (m *EditorInfo) String() string { return proto.CompactTextString(m) }
func (*EditorInfo) ProtoMessage()    {}
func (*EditorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{1}
}

func (m *EditorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditorInfo.Unmarshal(m, b)
}
func (m *EditorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditorInfo.Marshal(b, m, deterministic)
}
func (m *EditorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditorInfo.Merge(m, src)
}
func (m *EditorInfo) XXX_Size() int {
	return xxx_messageInfo_EditorInfo.Size(m)
}
func (m *EditorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EditorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EditorInfo proto.InternalMessageInfo

func (m *EditorInfo) GetEditorId() string {
	if m != nil {
		return m.EditorId
	}
	return ""
}

func (m *EditorInfo) GetEditorState() EditorState {
	if m != nil {
		return m.EditorState
	}
	return EditorState_editorProposed
}

type CommandJournalCreate struct {
	JournalId            string   `protobuf:"bytes,1,opt,name=journalId,proto3" json:"journalId,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DescriptionHash      string   `protobuf:"bytes,3,opt,name=descriptionHash,proto3" json:"descriptionHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandJournalCreate) Reset()         { *m = CommandJournalCreate{} }
func (m *CommandJournalCreate) String() string { return proto.CompactTextString(m) }
func (*CommandJournalCreate) ProtoMessage()    {}
func (*CommandJournalCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{2}
}

func (m *CommandJournalCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandJournalCreate.Unmarshal(m, b)
}
func (m *CommandJournalCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandJournalCreate.Marshal(b, m, deterministic)
}
func (m *CommandJournalCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandJournalCreate.Merge(m, src)
}
func (m *CommandJournalCreate) XXX_Size() int {
	return xxx_messageInfo_CommandJournalCreate.Size(m)
}
func (m *CommandJournalCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandJournalCreate.DiscardUnknown(m)
}

var xxx_messageInfo_CommandJournalCreate proto.InternalMessageInfo

func (m *CommandJournalCreate) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func (m *CommandJournalCreate) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CommandJournalCreate) GetDescriptionHash() string {
	if m != nil {
		return m.DescriptionHash
	}
	return ""
}

type CommandJournalUpdateProperties struct {
	JournalId             string        `protobuf:"bytes,1,opt,name=journalId,proto3" json:"journalId,omitempty"`
	TitleUpdate           *StringUpdate `protobuf:"bytes,2,opt,name=titleUpdate,proto3" json:"titleUpdate,omitempty"`
	DescriptionHashUpdate *StringUpdate `protobuf:"bytes,3,opt,name=descriptionHashUpdate,proto3" json:"descriptionHashUpdate,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}      `json:"-"`
	XXX_unrecognized      []byte        `json:"-"`
	XXX_sizecache         int32         `json:"-"`
}

func (m *CommandJournalUpdateProperties) Reset()         { *m = CommandJournalUpdateProperties{} }
func (m *CommandJournalUpdateProperties) String() string { return proto.CompactTextString(m) }
func (*CommandJournalUpdateProperties) ProtoMessage()    {}
func (*CommandJournalUpdateProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{3}
}

func (m *CommandJournalUpdateProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandJournalUpdateProperties.Unmarshal(m, b)
}
func (m *CommandJournalUpdateProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandJournalUpdateProperties.Marshal(b, m, deterministic)
}
func (m *CommandJournalUpdateProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandJournalUpdateProperties.Merge(m, src)
}
func (m *CommandJournalUpdateProperties) XXX_Size() int {
	return xxx_messageInfo_CommandJournalUpdateProperties.Size(m)
}
func (m *CommandJournalUpdateProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandJournalUpdateProperties.DiscardUnknown(m)
}

var xxx_messageInfo_CommandJournalUpdateProperties proto.InternalMessageInfo

func (m *CommandJournalUpdateProperties) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func (m *CommandJournalUpdateProperties) GetTitleUpdate() *StringUpdate {
	if m != nil {
		return m.TitleUpdate
	}
	return nil
}

func (m *CommandJournalUpdateProperties) GetDescriptionHashUpdate() *StringUpdate {
	if m != nil {
		return m.DescriptionHashUpdate
	}
	return nil
}

type CommandJournalAuthorizationUpdate struct {
	JournalId            string   `protobuf:"bytes,1,opt,name=journalId,proto3" json:"journalId,omitempty"`
	MakeSigned           bool     `protobuf:"varint,2,opt,name=makeSigned,proto3" json:"makeSigned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandJournalAuthorizationUpdate) Reset()         { *m = CommandJournalAuthorizationUpdate{} }
func (m *CommandJournalAuthorizationUpdate) String() string { return proto.CompactTextString(m) }
func (*CommandJournalAuthorizationUpdate) ProtoMessage()    {}
func (*CommandJournalAuthorizationUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{4}
}

func (m *CommandJournalAuthorizationUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandJournalAuthorizationUpdate.Unmarshal(m, b)
}
func (m *CommandJournalAuthorizationUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandJournalAuthorizationUpdate.Marshal(b, m, deterministic)
}
func (m *CommandJournalAuthorizationUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandJournalAuthorizationUpdate.Merge(m, src)
}
func (m *CommandJournalAuthorizationUpdate) XXX_Size() int {
	return xxx_messageInfo_CommandJournalAuthorizationUpdate.Size(m)
}
func (m *CommandJournalAuthorizationUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandJournalAuthorizationUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_CommandJournalAuthorizationUpdate proto.InternalMessageInfo

func (m *CommandJournalAuthorizationUpdate) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func (m *CommandJournalAuthorizationUpdate) GetMakeSigned() bool {
	if m != nil {
		return m.MakeSigned
	}
	return false
}

type CommandEditorResign struct {
	JournalId            string   `protobuf:"bytes,1,opt,name=journalId,proto3" json:"journalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandEditorResign) Reset()         { *m = CommandEditorResign{} }
func (m *CommandEditorResign) String() string { return proto.CompactTextString(m) }
func (*CommandEditorResign) ProtoMessage()    {}
func (*CommandEditorResign) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{5}
}

func (m *CommandEditorResign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandEditorResign.Unmarshal(m, b)
}
func (m *CommandEditorResign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandEditorResign.Marshal(b, m, deterministic)
}
func (m *CommandEditorResign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandEditorResign.Merge(m, src)
}
func (m *CommandEditorResign) XXX_Size() int {
	return xxx_messageInfo_CommandEditorResign.Size(m)
}
func (m *CommandEditorResign) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandEditorResign.DiscardUnknown(m)
}

var xxx_messageInfo_CommandEditorResign proto.InternalMessageInfo

func (m *CommandEditorResign) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

type CommandJournalEditorInvite struct {
	JournalId            string   `protobuf:"bytes,1,opt,name=journalId,proto3" json:"journalId,omitempty"`
	InvitedEditorId      string   `protobuf:"bytes,2,opt,name=invitedEditorId,proto3" json:"invitedEditorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandJournalEditorInvite) Reset()         { *m = CommandJournalEditorInvite{} }
func (m *CommandJournalEditorInvite) String() string { return proto.CompactTextString(m) }
func (*CommandJournalEditorInvite) ProtoMessage()    {}
func (*CommandJournalEditorInvite) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{6}
}

func (m *CommandJournalEditorInvite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandJournalEditorInvite.Unmarshal(m, b)
}
func (m *CommandJournalEditorInvite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandJournalEditorInvite.Marshal(b, m, deterministic)
}
func (m *CommandJournalEditorInvite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandJournalEditorInvite.Merge(m, src)
}
func (m *CommandJournalEditorInvite) XXX_Size() int {
	return xxx_messageInfo_CommandJournalEditorInvite.Size(m)
}
func (m *CommandJournalEditorInvite) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandJournalEditorInvite.DiscardUnknown(m)
}

var xxx_messageInfo_CommandJournalEditorInvite proto.InternalMessageInfo

func (m *CommandJournalEditorInvite) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func (m *CommandJournalEditorInvite) GetInvitedEditorId() string {
	if m != nil {
		return m.InvitedEditorId
	}
	return ""
}

type CommandEditorAcceptDuty struct {
	JournalId            string   `protobuf:"bytes,1,opt,name=journalId,proto3" json:"journalId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandEditorAcceptDuty) Reset()         { *m = CommandEditorAcceptDuty{} }
func (m *CommandEditorAcceptDuty) String() string { return proto.CompactTextString(m) }
func (*CommandEditorAcceptDuty) ProtoMessage()    {}
func (*CommandEditorAcceptDuty) Descriptor() ([]byte, []int) {
	return fileDescriptor_04fd98cceb1b9191, []int{7}
}

func (m *CommandEditorAcceptDuty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandEditorAcceptDuty.Unmarshal(m, b)
}
func (m *CommandEditorAcceptDuty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandEditorAcceptDuty.Marshal(b, m, deterministic)
}
func (m *CommandEditorAcceptDuty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandEditorAcceptDuty.Merge(m, src)
}
func (m *CommandEditorAcceptDuty) XXX_Size() int {
	return xxx_messageInfo_CommandEditorAcceptDuty.Size(m)
}
func (m *CommandEditorAcceptDuty) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandEditorAcceptDuty.DiscardUnknown(m)
}

var xxx_messageInfo_CommandEditorAcceptDuty proto.InternalMessageInfo

func (m *CommandEditorAcceptDuty) GetJournalId() string {
	if m != nil {
		return m.JournalId
	}
	return ""
}

func init() {
	proto.RegisterEnum("EditorState", EditorState_name, EditorState_value)
	proto.RegisterType((*StateJournal)(nil), "StateJournal")
	proto.RegisterType((*EditorInfo)(nil), "EditorInfo")
	proto.RegisterType((*CommandJournalCreate)(nil), "CommandJournalCreate")
	proto.RegisterType((*CommandJournalUpdateProperties)(nil), "CommandJournalUpdateProperties")
	proto.RegisterType((*CommandJournalAuthorizationUpdate)(nil), "CommandJournalAuthorizationUpdate")
	proto.RegisterType((*CommandEditorResign)(nil), "CommandEditorResign")
	proto.RegisterType((*CommandJournalEditorInvite)(nil), "CommandJournalEditorInvite")
	proto.RegisterType((*CommandEditorAcceptDuty)(nil), "CommandEditorAcceptDuty")
}

func init() { proto.RegisterFile("journal.proto", fileDescriptor_04fd98cceb1b9191) }

var fileDescriptor_04fd98cceb1b9191 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x35, 0x89, 0xdd, 0x8f, 0x9b, 0x6e, 0x77, 0x19, 0x57, 0x0c, 0x45, 0x96, 0x9a, 0xa7, 0xa0,
	0x50, 0xa1, 0x8b, 0xf8, 0xbc, 0x56, 0xc1, 0xf5, 0x45, 0x49, 0x11, 0xc4, 0xb7, 0x31, 0x73, 0xb7,
	0x7b, 0xb5, 0x99, 0x09, 0x93, 0xa9, 0xa0, 0xbf, 0xcb, 0xbf, 0xe4, 0xff, 0x58, 0x32, 0x33, 0xdb,
	0xa4, 0x25, 0x74, 0xdf, 0x72, 0xcf, 0xfd, 0x38, 0xe7, 0x9e, 0xb9, 0x81, 0x93, 0x9f, 0x6a, 0xad,
	0x25, 0x5f, 0x4d, 0x2b, 0xad, 0x8c, 0x1a, 0x0f, 0x0b, 0x55, 0x96, 0x4a, 0xba, 0x28, 0xfd, 0x1f,
	0xc0, 0x70, 0x61, 0xb8, 0xc1, 0x4f, 0xae, 0x88, 0x8d, 0x20, 0x24, 0x91, 0x04, 0x93, 0x20, 0x3b,
	0xce, 0x43, 0x12, 0xec, 0x39, 0x1c, 0x17, 0x1a, 0xb9, 0x41, 0xf1, 0x59, 0x26, 0xe1, 0x24, 0xc8,
	0xa2, 0xbc, 0x05, 0xd8, 0x05, 0x40, 0xa9, 0x04, 0xdd, 0x90, 0x4d, 0x47, 0x36, 0xdd, 0x41, 0xd8,
	0x39, 0x0c, 0x0c, 0x99, 0x15, 0x26, 0x8f, 0xed, 0x40, 0x17, 0xb0, 0x31, 0x1c, 0x51, 0xbd, 0xa0,
	0xa5, 0x44, 0x91, 0x0c, 0x26, 0x41, 0x76, 0x94, 0x6f, 0x62, 0x96, 0xc1, 0xa9, 0xc0, 0xba, 0xd0,
	0x54, 0x19, 0x52, 0xf2, 0x23, 0xaf, 0x6f, 0x93, 0x03, 0xdb, 0xbb, 0x0b, 0xb3, 0x57, 0x00, 0x28,
	0xc8, 0x28, 0x7d, 0x2d, 0x6f, 0x54, 0x72, 0x38, 0x89, 0xb2, 0x78, 0x16, 0x4f, 0x3f, 0x6c, 0xa0,
	0xbc, 0x93, 0x4e, 0xbf, 0x01, 0xb4, 0x99, 0x46, 0x80, 0xcf, 0xdd, 0xaf, 0xba, 0x89, 0xd9, 0x14,
	0x62, 0xf7, 0x6d, 0x6d, 0xb1, 0x2b, 0x8f, 0x66, 0x43, 0x3f, 0xd7, 0x62, 0x79, 0xb7, 0x20, 0x35,
	0x70, 0x3e, 0x57, 0x65, 0xc9, 0xa5, 0xf0, 0x16, 0xce, 0xad, 0x3b, 0x8d, 0x71, 0xde, 0xf8, 0x0d,
	0x49, 0x0b, 0xb4, 0xc6, 0x84, 0x5d, 0x63, 0x7a, 0x96, 0x8f, 0x7a, 0x97, 0x4f, 0xff, 0x05, 0x70,
	0xb1, 0x4d, 0xfb, 0xb5, 0x12, 0xdc, 0xe0, 0x17, 0xad, 0x2a, 0xd4, 0x86, 0xb0, 0x7e, 0x40, 0xc0,
	0x6b, 0x88, 0x2d, 0xa7, 0x6b, 0xb3, 0x32, 0xe2, 0xd9, 0xc9, 0x74, 0x61, 0x34, 0xc9, 0xa5, 0x03,
	0xf3, 0x6e, 0x05, 0x9b, 0xc3, 0xd3, 0x1d, 0x11, 0xbe, 0x35, 0xea, 0x6b, 0xed, 0xaf, 0x4d, 0x39,
	0xbc, 0xd8, 0x56, 0x7d, 0xb5, 0x36, 0xb7, 0x4a, 0xd3, 0x5f, 0xde, 0x14, 0x7a, 0xa6, 0xfd, 0xc2,
	0x9b, 0x93, 0xe3, 0xbf, 0xd0, 0x9f, 0x4f, 0x68, 0xcf, 0xa7, 0x83, 0xa4, 0x97, 0xf0, 0xc4, 0x53,
	0xb8, 0x27, 0xcb, 0xb1, 0xa6, 0xa5, 0xdc, 0x3f, 0x34, 0x15, 0x30, 0xde, 0xd6, 0x75, 0x7f, 0x2c,
	0xbf, 0xe9, 0x41, 0x41, 0x19, 0x9c, 0x92, 0xad, 0xf3, 0x84, 0xd7, 0xc2, 0x3f, 0xea, 0x2e, 0x9c,
	0xbe, 0x85, 0x67, 0x5b, 0xd2, 0xae, 0x8a, 0x02, 0x2b, 0xf3, 0x7e, 0x6d, 0xfe, 0xec, 0xa7, 0x78,
	0xf9, 0x06, 0xe2, 0xce, 0xfd, 0x31, 0x06, 0x23, 0x77, 0x81, 0xcd, 0x6b, 0xab, 0x1a, 0xc5, 0xd9,
	0xa3, 0x16, 0x73, 0x43, 0x51, 0x9c, 0x05, 0xef, 0x0e, 0xbf, 0x0f, 0x4a, 0x25, 0x70, 0xf5, 0xe3,
	0xc0, 0xfe, 0xec, 0x97, 0x77, 0x01, 0x00, 0x00, 0xff, 0xff, 0x28, 0x6b, 0xc7, 0x06, 0x0b, 0x04,
	0x00, 0x00,
}
