// Code generated by protoc-gen-go. DO NOT EDIT.
// source: settings.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StateSettings struct {
	CreatedOnOn          int64      `protobuf:"varint,1,opt,name=createdOnOn,proto3" json:"createdOnOn,omitempty"`
	ModifiedOn           int64      `protobuf:"varint,2,opt,name=modifiedOn,proto3" json:"modifiedOn,omitempty"`
	PriceList            *PriceList `protobuf:"bytes,3,opt,name=priceList,proto3" json:"priceList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StateSettings) Reset()         { *m = StateSettings{} }
func (m *StateSettings) String() string { return proto.CompactTextString(m) }
func (*StateSettings) ProtoMessage()    {}
func (*StateSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{0}
}

func (m *StateSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateSettings.Unmarshal(m, b)
}
func (m *StateSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateSettings.Marshal(b, m, deterministic)
}
func (m *StateSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateSettings.Merge(m, src)
}
func (m *StateSettings) XXX_Size() int {
	return xxx_messageInfo_StateSettings.Size(m)
}
func (m *StateSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_StateSettings.DiscardUnknown(m)
}

var xxx_messageInfo_StateSettings proto.InternalMessageInfo

func (m *StateSettings) GetCreatedOnOn() int64 {
	if m != nil {
		return m.CreatedOnOn
	}
	return 0
}

func (m *StateSettings) GetModifiedOn() int64 {
	if m != nil {
		return m.ModifiedOn
	}
	return 0
}

func (m *StateSettings) GetPriceList() *PriceList {
	if m != nil {
		return m.PriceList
	}
	return nil
}

type PriceList struct {
	PriceMajorEditSettings               int32    `protobuf:"varint,1,opt,name=priceMajorEditSettings,proto3" json:"priceMajorEditSettings,omitempty"`
	PriceMajorCreatePerson               int32    `protobuf:"varint,2,opt,name=priceMajorCreatePerson,proto3" json:"priceMajorCreatePerson,omitempty"`
	PriceMajorChangePersonAuthorization  int32    `protobuf:"varint,3,opt,name=priceMajorChangePersonAuthorization,proto3" json:"priceMajorChangePersonAuthorization,omitempty"`
	PriceMajorChangeJournalAuthorization int32    `protobuf:"varint,4,opt,name=priceMajorChangeJournalAuthorization,proto3" json:"priceMajorChangeJournalAuthorization,omitempty"`
	PricePersonEdit                      int32    `protobuf:"varint,5,opt,name=pricePersonEdit,proto3" json:"pricePersonEdit,omitempty"`
	PriceAuthorSubmitNewManuscript       int32    `protobuf:"varint,6,opt,name=priceAuthorSubmitNewManuscript,proto3" json:"priceAuthorSubmitNewManuscript,omitempty"`
	PriceAuthorSubmitNewVersion          int32    `protobuf:"varint,7,opt,name=priceAuthorSubmitNewVersion,proto3" json:"priceAuthorSubmitNewVersion,omitempty"`
	PriceAuthorAcceptAuthorship          int32    `protobuf:"varint,8,opt,name=priceAuthorAcceptAuthorship,proto3" json:"priceAuthorAcceptAuthorship,omitempty"`
	PriceReviewerSubmit                  int32    `protobuf:"varint,9,opt,name=priceReviewerSubmit,proto3" json:"priceReviewerSubmit,omitempty"`
	PriceEditorAllowManuscriptReview     int32    `protobuf:"varint,10,opt,name=priceEditorAllowManuscriptReview,proto3" json:"priceEditorAllowManuscriptReview,omitempty"`
	PriceEditorRejectManuscript          int32    `protobuf:"varint,11,opt,name=priceEditorRejectManuscript,proto3" json:"priceEditorRejectManuscript,omitempty"`
	PriceEditorPublishManuscript         int32    `protobuf:"varint,12,opt,name=priceEditorPublishManuscript,proto3" json:"priceEditorPublishManuscript,omitempty"`
	PriceEditorAssignManuscript          int32    `protobuf:"varint,13,opt,name=priceEditorAssignManuscript,proto3" json:"priceEditorAssignManuscript,omitempty"`
	PriceEditorCreateJournal             int32    `protobuf:"varint,14,opt,name=priceEditorCreateJournal,proto3" json:"priceEditorCreateJournal,omitempty"`
	PriceEditorCreateVolume              int32    `protobuf:"varint,15,opt,name=priceEditorCreateVolume,proto3" json:"priceEditorCreateVolume,omitempty"`
	PriceEditorEditJournal               int32    `protobuf:"varint,16,opt,name=priceEditorEditJournal,proto3" json:"priceEditorEditJournal,omitempty"`
	PriceEditorAddColleague              int32    `protobuf:"varint,17,opt,name=priceEditorAddColleague,proto3" json:"priceEditorAddColleague,omitempty"`
	PriceEditorAcceptDuty                int32    `protobuf:"varint,18,opt,name=priceEditorAcceptDuty,proto3" json:"priceEditorAcceptDuty,omitempty"`
	XXX_NoUnkeyedLiteral                 struct{} `json:"-"`
	XXX_unrecognized                     []byte   `json:"-"`
	XXX_sizecache                        int32    `json:"-"`
}

func (m *PriceList) Reset()         { *m = PriceList{} }
func (m *PriceList) String() string { return proto.CompactTextString(m) }
func (*PriceList) ProtoMessage()    {}
func (*PriceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{1}
}

func (m *PriceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceList.Unmarshal(m, b)
}
func (m *PriceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceList.Marshal(b, m, deterministic)
}
func (m *PriceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceList.Merge(m, src)
}
func (m *PriceList) XXX_Size() int {
	return xxx_messageInfo_PriceList.Size(m)
}
func (m *PriceList) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceList.DiscardUnknown(m)
}

var xxx_messageInfo_PriceList proto.InternalMessageInfo

func (m *PriceList) GetPriceMajorEditSettings() int32 {
	if m != nil {
		return m.PriceMajorEditSettings
	}
	return 0
}

func (m *PriceList) GetPriceMajorCreatePerson() int32 {
	if m != nil {
		return m.PriceMajorCreatePerson
	}
	return 0
}

func (m *PriceList) GetPriceMajorChangePersonAuthorization() int32 {
	if m != nil {
		return m.PriceMajorChangePersonAuthorization
	}
	return 0
}

func (m *PriceList) GetPriceMajorChangeJournalAuthorization() int32 {
	if m != nil {
		return m.PriceMajorChangeJournalAuthorization
	}
	return 0
}

func (m *PriceList) GetPricePersonEdit() int32 {
	if m != nil {
		return m.PricePersonEdit
	}
	return 0
}

func (m *PriceList) GetPriceAuthorSubmitNewManuscript() int32 {
	if m != nil {
		return m.PriceAuthorSubmitNewManuscript
	}
	return 0
}

func (m *PriceList) GetPriceAuthorSubmitNewVersion() int32 {
	if m != nil {
		return m.PriceAuthorSubmitNewVersion
	}
	return 0
}

func (m *PriceList) GetPriceAuthorAcceptAuthorship() int32 {
	if m != nil {
		return m.PriceAuthorAcceptAuthorship
	}
	return 0
}

func (m *PriceList) GetPriceReviewerSubmit() int32 {
	if m != nil {
		return m.PriceReviewerSubmit
	}
	return 0
}

func (m *PriceList) GetPriceEditorAllowManuscriptReview() int32 {
	if m != nil {
		return m.PriceEditorAllowManuscriptReview
	}
	return 0
}

func (m *PriceList) GetPriceEditorRejectManuscript() int32 {
	if m != nil {
		return m.PriceEditorRejectManuscript
	}
	return 0
}

func (m *PriceList) GetPriceEditorPublishManuscript() int32 {
	if m != nil {
		return m.PriceEditorPublishManuscript
	}
	return 0
}

func (m *PriceList) GetPriceEditorAssignManuscript() int32 {
	if m != nil {
		return m.PriceEditorAssignManuscript
	}
	return 0
}

func (m *PriceList) GetPriceEditorCreateJournal() int32 {
	if m != nil {
		return m.PriceEditorCreateJournal
	}
	return 0
}

func (m *PriceList) GetPriceEditorCreateVolume() int32 {
	if m != nil {
		return m.PriceEditorCreateVolume
	}
	return 0
}

func (m *PriceList) GetPriceEditorEditJournal() int32 {
	if m != nil {
		return m.PriceEditorEditJournal
	}
	return 0
}

func (m *PriceList) GetPriceEditorAddColleague() int32 {
	if m != nil {
		return m.PriceEditorAddColleague
	}
	return 0
}

func (m *PriceList) GetPriceEditorAcceptDuty() int32 {
	if m != nil {
		return m.PriceEditorAcceptDuty
	}
	return 0
}

type CommandBootstrap struct {
	PriceList            *PriceList           `protobuf:"bytes,1,opt,name=priceList,proto3" json:"priceList,omitempty"`
	FirstMajor           *CommandPersonCreate `protobuf:"bytes,2,opt,name=firstMajor,proto3" json:"firstMajor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CommandBootstrap) Reset()         { *m = CommandBootstrap{} }
func (m *CommandBootstrap) String() string { return proto.CompactTextString(m) }
func (*CommandBootstrap) ProtoMessage()    {}
func (*CommandBootstrap) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{2}
}

func (m *CommandBootstrap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandBootstrap.Unmarshal(m, b)
}
func (m *CommandBootstrap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandBootstrap.Marshal(b, m, deterministic)
}
func (m *CommandBootstrap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandBootstrap.Merge(m, src)
}
func (m *CommandBootstrap) XXX_Size() int {
	return xxx_messageInfo_CommandBootstrap.Size(m)
}
func (m *CommandBootstrap) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandBootstrap.DiscardUnknown(m)
}

var xxx_messageInfo_CommandBootstrap proto.InternalMessageInfo

func (m *CommandBootstrap) GetPriceList() *PriceList {
	if m != nil {
		return m.PriceList
	}
	return nil
}

func (m *CommandBootstrap) GetFirstMajor() *CommandPersonCreate {
	if m != nil {
		return m.FirstMajor
	}
	return nil
}

type CommandSettingsUpdate struct {
	PriceMajorEditSettingsUpdate               *IntUpdate `protobuf:"bytes,1,opt,name=priceMajorEditSettingsUpdate,proto3" json:"priceMajorEditSettingsUpdate,omitempty"`
	PriceMajorCreatePersonUpdate               *IntUpdate `protobuf:"bytes,2,opt,name=priceMajorCreatePersonUpdate,proto3" json:"priceMajorCreatePersonUpdate,omitempty"`
	PriceMajorChangePersonAuthorizationUpdate  *IntUpdate `protobuf:"bytes,3,opt,name=priceMajorChangePersonAuthorizationUpdate,proto3" json:"priceMajorChangePersonAuthorizationUpdate,omitempty"`
	PriceMajorChangeJournalAuthorizationUpdate *IntUpdate `protobuf:"bytes,4,opt,name=priceMajorChangeJournalAuthorizationUpdate,proto3" json:"priceMajorChangeJournalAuthorizationUpdate,omitempty"`
	PricePersonEditUpdate                      *IntUpdate `protobuf:"bytes,5,opt,name=pricePersonEditUpdate,proto3" json:"pricePersonEditUpdate,omitempty"`
	PriceAuthorSubmitNewManuscriptUpdate       *IntUpdate `protobuf:"bytes,6,opt,name=priceAuthorSubmitNewManuscriptUpdate,proto3" json:"priceAuthorSubmitNewManuscriptUpdate,omitempty"`
	PriceAuthorSubmitNewVersionUpdate          *IntUpdate `protobuf:"bytes,7,opt,name=priceAuthorSubmitNewVersionUpdate,proto3" json:"priceAuthorSubmitNewVersionUpdate,omitempty"`
	PriceAuthorAcceptAuthorshipUpdate          *IntUpdate `protobuf:"bytes,8,opt,name=priceAuthorAcceptAuthorshipUpdate,proto3" json:"priceAuthorAcceptAuthorshipUpdate,omitempty"`
	PriceReviewerSubmitUpdate                  *IntUpdate `protobuf:"bytes,9,opt,name=priceReviewerSubmitUpdate,proto3" json:"priceReviewerSubmitUpdate,omitempty"`
	PriceEditorAllowManuscriptReviewUpdate     *IntUpdate `protobuf:"bytes,10,opt,name=priceEditorAllowManuscriptReviewUpdate,proto3" json:"priceEditorAllowManuscriptReviewUpdate,omitempty"`
	PriceEditorRejectManuscriptUpdate          *IntUpdate `protobuf:"bytes,11,opt,name=priceEditorRejectManuscriptUpdate,proto3" json:"priceEditorRejectManuscriptUpdate,omitempty"`
	PriceEditorPublishManuscriptUpdate         *IntUpdate `protobuf:"bytes,12,opt,name=priceEditorPublishManuscriptUpdate,proto3" json:"priceEditorPublishManuscriptUpdate,omitempty"`
	PriceEditorAssignManuscriptUpdate          *IntUpdate `protobuf:"bytes,13,opt,name=priceEditorAssignManuscriptUpdate,proto3" json:"priceEditorAssignManuscriptUpdate,omitempty"`
	PriceEditorCreateJournalUpdate             *IntUpdate `protobuf:"bytes,14,opt,name=priceEditorCreateJournalUpdate,proto3" json:"priceEditorCreateJournalUpdate,omitempty"`
	PriceEditorCreateVolumeUpdate              *IntUpdate `protobuf:"bytes,15,opt,name=priceEditorCreateVolumeUpdate,proto3" json:"priceEditorCreateVolumeUpdate,omitempty"`
	PriceEditorEditJournalUpdate               *IntUpdate `protobuf:"bytes,16,opt,name=priceEditorEditJournalUpdate,proto3" json:"priceEditorEditJournalUpdate,omitempty"`
	PriceEditorAddColleagueUpdate              *IntUpdate `protobuf:"bytes,17,opt,name=priceEditorAddColleagueUpdate,proto3" json:"priceEditorAddColleagueUpdate,omitempty"`
	PriceEditorAcceptDutyUpdate                *IntUpdate `protobuf:"bytes,18,opt,name=priceEditorAcceptDutyUpdate,proto3" json:"priceEditorAcceptDutyUpdate,omitempty"`
	XXX_NoUnkeyedLiteral                       struct{}   `json:"-"`
	XXX_unrecognized                           []byte     `json:"-"`
	XXX_sizecache                              int32      `json:"-"`
}

func (m *CommandSettingsUpdate) Reset()         { *m = CommandSettingsUpdate{} }
func (m *CommandSettingsUpdate) String() string { return proto.CompactTextString(m) }
func (*CommandSettingsUpdate) ProtoMessage()    {}
func (*CommandSettingsUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{3}
}

func (m *CommandSettingsUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandSettingsUpdate.Unmarshal(m, b)
}
func (m *CommandSettingsUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandSettingsUpdate.Marshal(b, m, deterministic)
}
func (m *CommandSettingsUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandSettingsUpdate.Merge(m, src)
}
func (m *CommandSettingsUpdate) XXX_Size() int {
	return xxx_messageInfo_CommandSettingsUpdate.Size(m)
}
func (m *CommandSettingsUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandSettingsUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_CommandSettingsUpdate proto.InternalMessageInfo

func (m *CommandSettingsUpdate) GetPriceMajorEditSettingsUpdate() *IntUpdate {
	if m != nil {
		return m.PriceMajorEditSettingsUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceMajorCreatePersonUpdate() *IntUpdate {
	if m != nil {
		return m.PriceMajorCreatePersonUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceMajorChangePersonAuthorizationUpdate() *IntUpdate {
	if m != nil {
		return m.PriceMajorChangePersonAuthorizationUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceMajorChangeJournalAuthorizationUpdate() *IntUpdate {
	if m != nil {
		return m.PriceMajorChangeJournalAuthorizationUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPricePersonEditUpdate() *IntUpdate {
	if m != nil {
		return m.PricePersonEditUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceAuthorSubmitNewManuscriptUpdate() *IntUpdate {
	if m != nil {
		return m.PriceAuthorSubmitNewManuscriptUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceAuthorSubmitNewVersionUpdate() *IntUpdate {
	if m != nil {
		return m.PriceAuthorSubmitNewVersionUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceAuthorAcceptAuthorshipUpdate() *IntUpdate {
	if m != nil {
		return m.PriceAuthorAcceptAuthorshipUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceReviewerSubmitUpdate() *IntUpdate {
	if m != nil {
		return m.PriceReviewerSubmitUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceEditorAllowManuscriptReviewUpdate() *IntUpdate {
	if m != nil {
		return m.PriceEditorAllowManuscriptReviewUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceEditorRejectManuscriptUpdate() *IntUpdate {
	if m != nil {
		return m.PriceEditorRejectManuscriptUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceEditorPublishManuscriptUpdate() *IntUpdate {
	if m != nil {
		return m.PriceEditorPublishManuscriptUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceEditorAssignManuscriptUpdate() *IntUpdate {
	if m != nil {
		return m.PriceEditorAssignManuscriptUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceEditorCreateJournalUpdate() *IntUpdate {
	if m != nil {
		return m.PriceEditorCreateJournalUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceEditorCreateVolumeUpdate() *IntUpdate {
	if m != nil {
		return m.PriceEditorCreateVolumeUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceEditorEditJournalUpdate() *IntUpdate {
	if m != nil {
		return m.PriceEditorEditJournalUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceEditorAddColleagueUpdate() *IntUpdate {
	if m != nil {
		return m.PriceEditorAddColleagueUpdate
	}
	return nil
}

func (m *CommandSettingsUpdate) GetPriceEditorAcceptDutyUpdate() *IntUpdate {
	if m != nil {
		return m.PriceEditorAcceptDutyUpdate
	}
	return nil
}

func init() {
	proto.RegisterType((*StateSettings)(nil), "StateSettings")
	proto.RegisterType((*PriceList)(nil), "PriceList")
	proto.RegisterType((*CommandBootstrap)(nil), "CommandBootstrap")
	proto.RegisterType((*CommandSettingsUpdate)(nil), "CommandSettingsUpdate")
}

func init() { proto.RegisterFile("settings.proto", fileDescriptor_6c7cab62fa432213) }

var fileDescriptor_6c7cab62fa432213 = []byte{
	// 773 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xdb, 0x6f, 0xd3, 0x30,
	0x18, 0xc5, 0xd5, 0x6d, 0xdd, 0xd6, 0xaf, 0xdd, 0xed, 0x83, 0x41, 0xb8, 0x4d, 0xa5, 0x20, 0x54,
	0x78, 0x98, 0xd0, 0x98, 0x10, 0xe2, 0x69, 0xdd, 0x00, 0xc1, 0xb4, 0x4b, 0x95, 0x89, 0x09, 0xed,
	0x01, 0x29, 0x4d, 0xbc, 0xd6, 0x55, 0x12, 0x47, 0x89, 0xc3, 0x04, 0xfc, 0x61, 0xfc, 0x71, 0xbc,
	0xa0, 0x3a, 0x6e, 0xe6, 0xc6, 0x49, 0x1a, 0x5e, 0xa6, 0xc5, 0xe7, 0x9c, 0x9f, 0xbf, 0x44, 0xc9,
	0x71, 0x61, 0x3d, 0x22, 0x9c, 0x53, 0x7f, 0x18, 0xed, 0x06, 0x21, 0xe3, 0xec, 0x61, 0xcb, 0x66,
	0x9e, 0xc7, 0xfc, 0xe9, 0x55, 0x40, 0xc2, 0x68, 0x7a, 0xd5, 0xf9, 0x0d, 0x6b, 0x17, 0xdc, 0xe2,
	0xe4, 0x42, 0x46, 0xb0, 0x0d, 0x4d, 0x3b, 0x24, 0x16, 0x27, 0xce, 0xb9, 0x7f, 0xee, 0x1b, 0xb5,
	0x76, 0xad, 0xbb, 0x68, 0xaa, 0x4b, 0xb8, 0x03, 0xe0, 0x31, 0x87, 0x5e, 0xd3, 0xc9, 0xb5, 0xb1,
	0x20, 0x0c, 0xca, 0x0a, 0x76, 0xa1, 0x11, 0x84, 0xd4, 0x26, 0x27, 0x34, 0xe2, 0xc6, 0x62, 0xbb,
	0xd6, 0x6d, 0xee, 0xc1, 0x6e, 0x7f, 0xba, 0x62, 0xde, 0x8a, 0x9d, 0xbf, 0xab, 0xd0, 0x48, 0x05,
	0x7c, 0x0b, 0xf7, 0x84, 0x74, 0x6a, 0x8d, 0x59, 0xf8, 0xd1, 0xa1, 0x7c, 0x3a, 0x93, 0x18, 0xa2,
	0x6e, 0x16, 0xa8, 0xb3, 0xb9, 0x23, 0x31, 0x68, 0x5f, 0xdc, 0xa2, 0x98, 0x6d, 0x26, 0xa7, 0xaa,
	0xd8, 0x87, 0x67, 0x8a, 0x32, 0xb2, 0xfc, 0xa1, 0x54, 0x7a, 0x31, 0x1f, 0xb1, 0x90, 0xfe, 0xb2,
	0x38, 0x65, 0xbe, 0xb8, 0x83, 0xba, 0x59, 0xc5, 0x8a, 0x26, 0x3c, 0xcf, 0xda, 0x8e, 0x59, 0x1c,
	0xfa, 0x96, 0x3b, 0x8b, 0x5c, 0x12, 0xc8, 0x4a, 0x5e, 0xec, 0xc2, 0x86, 0xf0, 0x25, 0xfb, 0x4d,
	0x6e, 0xdc, 0xa8, 0x8b, 0x78, 0x76, 0x19, 0x3f, 0xc1, 0x8e, 0x58, 0x4a, 0xf2, 0x17, 0xf1, 0xc0,
	0xa3, 0xfc, 0x8c, 0xdc, 0x9c, 0x5a, 0x7e, 0x1c, 0xd9, 0x21, 0x0d, 0xb8, 0xb1, 0x2c, 0x82, 0x73,
	0x5c, 0x78, 0x00, 0x8f, 0xf2, 0x1c, 0x97, 0x24, 0x8c, 0x26, 0xc3, 0xaf, 0x08, 0x48, 0x99, 0x25,
	0x43, 0xe8, 0xd9, 0x36, 0x09, 0x78, 0xf2, 0x7f, 0x34, 0xa2, 0x81, 0xb1, 0xaa, 0x11, 0xb2, 0x16,
	0x7c, 0x0d, 0x77, 0x84, 0x6c, 0x92, 0x1f, 0x94, 0xdc, 0x10, 0xb9, 0x85, 0xd1, 0x10, 0xc9, 0x3c,
	0x09, 0x8f, 0xa1, 0x2d, 0x96, 0x27, 0x8f, 0x82, 0x85, 0x3d, 0xd7, 0x65, 0xca, 0x3d, 0x25, 0x5e,
	0x03, 0x44, 0x7c, 0xae, 0x2f, 0x9d, 0x3f, 0xf1, 0x98, 0x64, 0x4c, 0x6c, 0xae, 0x3c, 0xc6, 0xa6,
	0x32, 0x7f, 0xbe, 0x05, 0x0f, 0xe1, 0xb1, 0x22, 0xf7, 0xe3, 0x81, 0x4b, 0xa3, 0x91, 0x82, 0x68,
	0x09, 0x44, 0xa9, 0x27, 0x33, 0x45, 0x2f, 0x8a, 0xe8, 0xd0, 0x57, 0x10, 0x6b, 0xda, 0x14, 0x59,
	0x0b, 0xbe, 0x07, 0x43, 0x91, 0x93, 0x97, 0x5f, 0xbe, 0x64, 0xc6, 0xba, 0x88, 0x17, 0xea, 0xf8,
	0x0e, 0xee, 0x6b, 0xda, 0x25, 0x73, 0x63, 0x8f, 0x18, 0x1b, 0x22, 0x5a, 0x24, 0xa7, 0xdf, 0x63,
	0x22, 0x4d, 0xfe, 0x4e, 0xf7, 0xdc, 0x54, 0xbe, 0x47, 0x4d, 0xcd, 0xec, 0xd8, 0x73, 0x9c, 0x23,
	0xe6, 0xba, 0xc4, 0x1a, 0xc6, 0xc4, 0xd8, 0xd2, 0x76, 0x54, 0x65, 0xdc, 0x87, 0x6d, 0x55, 0x12,
	0x2f, 0xd3, 0x87, 0x98, 0xff, 0x34, 0x50, 0xe4, 0xf2, 0xc5, 0x4e, 0x08, 0x9b, 0x47, 0xcc, 0xf3,
	0x2c, 0xdf, 0x39, 0x64, 0x8c, 0x47, 0x3c, 0xb4, 0x82, 0xd9, 0xee, 0xaa, 0x95, 0x74, 0x17, 0xee,
	0x03, 0x5c, 0xd3, 0x30, 0xe2, 0xe2, 0xfb, 0x15, 0x4d, 0xd3, 0xdc, 0xbb, 0xbb, 0x2b, 0x81, 0xc9,
	0x57, 0x99, 0x3c, 0x15, 0x53, 0xf1, 0x75, 0xfe, 0xb4, 0x60, 0x5b, 0x7a, 0xa6, 0xfd, 0xf5, 0x35,
	0x70, 0x2c, 0x4e, 0xf0, 0x4c, 0xbe, 0x31, 0x5a, 0xbf, 0x25, 0x7a, 0x3a, 0xcc, 0x17, 0x9f, 0x27,
	0x2b, 0x66, 0xa9, 0x7f, 0x96, 0xa7, 0xf6, 0x9e, 0xe4, 0x2d, 0x94, 0xf1, 0x74, 0x3f, 0x8e, 0xe0,
	0x65, 0x85, 0x0a, 0x94, 0xf0, 0x45, 0x0d, 0x5e, 0x3d, 0x8c, 0x63, 0x78, 0x55, 0xa5, 0x19, 0xe5,
	0x56, 0x4b, 0xda, 0x56, 0xff, 0x91, 0xc6, 0x03, 0xf9, 0xe6, 0xdc, 0xd6, 0xa8, 0xc4, 0xd6, 0x35,
	0x6c, 0xbe, 0x11, 0xbf, 0xcb, 0xce, 0x2f, 0xec, 0x53, 0x09, 0x5c, 0xd6, 0x80, 0x95, 0x72, 0xf8,
	0x0d, 0x9e, 0x96, 0x54, 0xad, 0x84, 0xaf, 0x68, 0xf0, 0xf9, 0xa1, 0x0c, 0x39, 0x5b, 0xc1, 0x92,
	0xbc, 0x5a, 0x4a, 0xce, 0x0f, 0xe1, 0x67, 0x78, 0x90, 0x53, 0xd1, 0x92, 0xd8, 0xd0, 0x88, 0xc5,
	0x66, 0x1c, 0xc0, 0x8b, 0x79, 0x6d, 0x2d, 0xb1, 0xa0, 0x61, 0x2b, 0x26, 0xd3, 0xe7, 0x90, 0x5f,
	0xe5, 0x12, 0xdf, 0x2c, 0x78, 0x0e, 0x65, 0x21, 0xbc, 0x82, 0x4e, 0x59, 0xc3, 0x4b, 0x74, 0x4b,
	0x43, 0x57, 0x48, 0x65, 0xa6, 0xce, 0x56, 0xbf, 0x44, 0xaf, 0x95, 0x4e, 0x9d, 0x1f, 0x42, 0x53,
	0xfe, 0x8e, 0xc8, 0x39, 0x15, 0x24, 0x76, 0x5d, 0xc3, 0xce, 0x49, 0x60, 0x1f, 0x9e, 0x14, 0x1c,
	0x17, 0x12, 0xb9, 0xa1, 0x21, 0xcb, 0x03, 0x69, 0xbf, 0x69, 0xe7, 0x88, 0x04, 0x6e, 0x16, 0xf4,
	0x5b, 0x81, 0x3f, 0x33, 0xa1, 0x7a, 0xbc, 0x48, 0xe0, 0x56, 0xe9, 0x84, 0x7a, 0x00, 0x4f, 0x66,
	0xcf, 0xef, 0xf4, 0xe0, 0x91, 0x3c, 0xd4, 0x78, 0x65, 0xf6, 0xc3, 0x95, 0xab, 0xba, 0xc7, 0x1c,
	0xe2, 0x0e, 0x96, 0xc5, 0x0f, 0xf7, 0x37, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xa5, 0x91,
	0x26, 0xe6, 0x0b, 0x00, 0x00,
}
